### ISSUE TITLE
fatal error: could not build module 'flutter_fai_umeng'

### ISSUE THREAD

**Issue by zhangweiwei0326** [zhaolongs/flutter_fai_umeng#3]
ios 编译报错

**Comment by zhaolongs** [comment]
有再详细点的 日志信息没

**Comment by zhangweiwei0326** [comment]
While building module 'flutter_fai_umeng' imported from /Users/weiwei/Documents/byapp/ios/Runner/GeneratedPluginRegistrant.m:74:
    In file included from <module-includes>:1:
    In file included from /Users/weiwei/Documents/byapp/build/ios/Debug-iphonesimulator/flutter_fai_umeng/flutter_fai_umeng.framework/Headers/flutter_fai_umeng-umbrella.h:14:
    /Users/weiwei/Documents/byapp/build/ios/Debug-iphonesimulator/flutter_fai_umeng/flutter_fai_umeng.framework/Headers/UMengRecordTool.h:11:9: error: include of non-modular header inside framework module 'flutter_fai_umeng.UMengRecordTool': '/Users/weiwei/Documents/byapp/ios/Pods/UMCCommon/UMCommon.framework/Headers/UMCommon.h' [-Werror,-Wnon-modular-include-in-framework-module]
    #import <UMCommon/UMCommon.h>
            ^
    /Users/weiwei/Documents/byapp/build/ios/Debug-iphonesimulator/flutter_fai_umeng/flutter_fai_umeng.framework/Headers/UMengRecordTool.h:12:9: error: include of non-modular header inside framework module 'flutter_fai_umeng.UMengRecordTool': '/Users/weiwei/Documents/byapp/ios/Pods/UMCCommonLog/UMCommonLog/UMCommonLog.framework/Headers/UMCommonLogHeaders.h' [-Werror,-Wnon-modular-include-in-framework-module]
    #import <UMCommonLog/UMCommonLogHeaders.h>
            ^
    /Users/weiwei/Documents/byapp/build/ios/Debug-iphonesimulator/flutter_fai_umeng/flutter_fai_umeng.framework/Headers/UMengRecordTool.h:13:9: error: include of non-modular header inside framework module 'flutter_fai_umeng.UMengRecordTool': '/Users/weiwei/Documents/byapp/ios/Pods/UMCAnalytics/UMAnalytics.framework/Headers/MobClick.h' [-Werror,-Wnon-modular-include-in-framework-module]
    #import <UMAnalytics/MobClick.h>
            ^
    While building module 'flutter_fai_umeng' imported from /Users/weiwei/Documents/byapp/ios/Runner/GeneratedPluginRegistrant.m:74:
    In file included from <module-includes>:1:
    In file included from /Users/weiwei/Documents/byapp/build/ios/Debug-iphonesimulator/flutter_fai_umeng/flutter_fai_umeng.framework/Headers/flutter_fai_umeng-umbrella.h:14:
    In file included from /Users/weiwei/Documents/byapp/build/ios/Debug-iphonesimulator/flutter_fai_umeng/flutter_fai_umeng.framework/Headers/UMengRecordTool.h:13:
    /Users/weiwei/Documents/byapp/ios/Pods/UMCAnalytics/UMAnalytics.framework/Headers/MobClick.h:10:29: warning: this block declaration is not a prototype [-Wstrict-prototypes]
    typedef void(^CallbackBlock)();
                                ^
                                 void
    1 warning and 3 errors generated.
    /Users/weiwei/Documents/byapp/ios/Runner/GeneratedPluginRegistrant.m:74:9: fatal error: could not build module 'flutter_fai_umeng'
    #import <flutter_fai_umeng/FlutterFaiUmengPlugin.h>
     ~~~~~~~^
    1 warning and 4 errors generated.

**Comment by ZD-Yin** [comment]
同遇到这个问题，bulid 无法通过

**Comment by kennenfromchina** [comment]
换个分支试试

2020_06_18_Add_UMCPush

**Comment by YZDCDL** [comment]
https://www.gitmemory.com/issue/OpenFlutter/amap_base_flutter/85/497257820

**Comment by ZD-Yin** [comment]
解决了，阔以参看这个：    https://www.gitmemory.com/issue/OpenFlutter/amap_base_flutter/85/497257820

**Comment by zhaolongs** [comment]
ok
